apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector: ## link entre service e deployment onde esse expõe o outro
    app: flask-app #app definido no outro arquivo
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer